In [1]:
students = [  
   {  
      "name":"arun",
      "gender":"Male",
      "marks":[56,67,87,65,43]
   },
   {  
      "name":"rajesh",
      "gender":"Male",
      "marks":[12,43,23,40,43]
   },
   {  
      "name":"moorthy",
      "gender":"Male",
      "marks":[56,78,87,54,65]
   },
   {  
      "name":"raja",
      "gender":"Male",
      "marks":[67,34,87,56,78]
   },
   {  
      "name":"usha",
      "gender":"Female",
      "marks":[17,12,42,23,43]
   },
   {  
      "name":"priya",
      "gender":"Female",
      "marks":[75,67,87,65,85]
   },
   {  
      "name":"Sundar",
      "gender":"Male",
      "marks":[56,67,87,65,67]
   },
   {  
      "name":"Kavitha",
      "gender":"Female",
      "marks":[65,67,64,65,62]
   },
   {  
      "name":"Dinesh",
      "gender":"Male",
      "marks":[56,67,87,65,56]
   },
   {  
      "name":"Hema",
      "gender":"Female",
      "marks":[78,98,79,75,83]
   },
   {  
      "name":"Gowri",
      "gender":"Female",
      "marks":[88,90,87,89,87]
   },
   {  
      "name":"Ram",
      "gender":"Male",
      "marks":[56,89,54,65,67]
   },
   {  
      "name":"Murugan",
      "gender":"Male",
      "marks":[67,98,87,87,56]
   },
   {  
      "name":"Jenifer",
      "gender":"Female",
      "marks":[67,45,46,43,23]
   }
]

In [2]:
def findTotal(marks):
    return sum(marks)

def findResult(marks, passMark=45):
    for mark in marks:
        if mark < passMark:
            result = 'Fail'
            break
    else:
        result = 'Pass'
    return result

def findPercentage(marks):
    return round(sum(marks)/len(marks),2)

In [3]:
def calculateResult(student):
    passMark=45
    student['total'] = findTotal(student['marks'])
    student['result'] = findResult(student['marks'], passMark)      
    if student['result'] == 'Pass':
        student['percentage'] = findPercentage(student['marks'])
    return student

In [4]:
list(map(calculateResult, students))

[{'name': 'arun',
  'gender': 'Male',
  'marks': [56, 67, 87, 65, 43],
  'total': 318,
  'result': 'Fail'},
 {'name': 'rajesh',
  'gender': 'Male',
  'marks': [12, 43, 23, 40, 43],
  'total': 161,
  'result': 'Fail'},
 {'name': 'moorthy',
  'gender': 'Male',
  'marks': [56, 78, 87, 54, 65],
  'total': 340,
  'result': 'Pass',
  'percentage': 68.0},
 {'name': 'raja',
  'gender': 'Male',
  'marks': [67, 34, 87, 56, 78],
  'total': 322,
  'result': 'Fail'},
 {'name': 'usha',
  'gender': 'Female',
  'marks': [17, 12, 42, 23, 43],
  'total': 137,
  'result': 'Fail'},
 {'name': 'priya',
  'gender': 'Female',
  'marks': [75, 67, 87, 65, 85],
  'total': 379,
  'result': 'Pass',
  'percentage': 75.8},
 {'name': 'Sundar',
  'gender': 'Male',
  'marks': [56, 67, 87, 65, 67],
  'total': 342,
  'result': 'Pass',
  'percentage': 68.4},
 {'name': 'Kavitha',
  'gender': 'Female',
  'marks': [65, 67, 64, 65, 62],
  'total': 323,
  'result': 'Pass',
  'percentage': 64.6},
 {'name': 'Dinesh',
  'gender': 'Male',
  'marks': [56, 67, 87, 65, 56],
  'total': 331,
  'result': 'Pass',
  'percentage': 66.2},
 {'name': 'Hema',
  'gender': 'Female',
  'marks': [78, 98, 79, 75, 83],
  'total': 413,
  'result': 'Pass',
  'percentage': 82.6},
 {'name': 'Gowri',
  'gender': 'Female',
  'marks': [88, 90, 87, 89, 87],
  'total': 441,
  'result': 'Pass',
  'percentage': 88.2},
 {'name': 'Ram',
  'gender': 'Male',
  'marks': [56, 89, 54, 65, 67],
  'total': 331,
  'result': 'Pass',
  'percentage': 66.2},
 {'name': 'Murugan',
  'gender': 'Male',
  'marks': [67, 98, 87, 87, 56],
  'total': 395,
  'result': 'Pass',
  'percentage': 79.0},
 {'name': 'Jenifer',
  'gender': 'Female',
  'marks': [67, 45, 46, 43, 23],
  'total': 224,
  'result': 'Fail'}]